#!/bin/bash

GRAALENV_DIR=`dirname ${BASH_SOURCE[0]}`
GRAALENV_DIR=`readlink -f ${GRAALENV_DIR}`

source $GRAALENV_DIR/lib/constants.sh

graalenv() {
    source $GRAALENV_DIR/lib/functions.sh
    for i in `typeset -F`; do
	if [[ "$i" == __graal_env_cmd_$1 ]]; then
	    __graal_env_cmd_$1 "${@:2}"
	    local exitcode=$?
	    __graal_env_unset_all
	    return $exitcode
	fi
    done
    __graal_env_cmd_help
    __graal_env_unset_all
}

mx() {
    source $GRAALENV_DIR/lib/functions.sh
    if [ "$1" == "selfupdate" ]; then
	__graal_env_cmd_update_mx
	return $?
    else
	__graal_env_mx "$@"
	local exitcode=$?
	__graal_env_unset_all
	return $exitcode
    fi
}

netbeans() {
    source $GRAALENV_DIR/lib/functions.sh
    if [ "$1" == "selfupdate" ]; then
	__graal_env_update_netbeans
	return $?
    else
	__graal_env_netbeans "$@"
	local exitcode=$?
	__graal_env_unset_all
	return $exitcode
    fi
}

__graal_env_install_bash_completion() {
    source $GRAALENV_DIR/lib/functions.sh
    GRAALENV_COMMANDS="$(__graal_env_determine_commands)"
    MX_COMMANDS=

    _graalenv()
    {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	if [[ "$prev" == "use" ]]; then
	    opts="$(graalenv list --porcelain)"	    
	    COMPREPLY=( $(compgen -W "${opts}" -- ${cur##use}) )
	elif [[ "$prev" == "uninstall" ]]; then
	    opts="$(graalenv list --porcelain)"
	    COMPREPLY=( $(compgen -W "${opts}" -- ${cur##use}) )
	elif [[ "$prev" == "install" ]]; then
	    opts="$(graalenv available)"
	    COMPREPLY=( $(compgen -W "${opts}" -- ${cur##install}) )
	else
	    COMPREPLY=( $(compgen -W "${GRAALENV_COMMANDS}" -- ${cur}) )
	fi
	return 0
    }
    complete -F _graalenv graalenv

    _mx()
    {
	if [ -z "$MX_COMMANDS" ]; then
	    MX_COMMANDS=$(mx help | grep -A100 "available commands:" | tail -n +2 | cut -f 2 -d' ')
	fi
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	if [[ "$prev" == "mx" ]]; then
	    opts="selfupdate $MX_COMMANDS"
	    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
	fi
	return 0
    }
    complete -F _mx mx

    __graal_env_unset_all
}

__graal_env_install_bash_completion
unset -f __graal_env_install_bash_completion
